export const CATEGORIES = [
  { id: 'general',  label: '💀 General',       desc: 'A little bit of everything. Mostly pain.' },
  { id: 'science',  label: '🧪 Science',        desc: 'For people who peaked in chemistry class.' },
  { id: 'history',  label: '⚰️ History',        desc: 'Dead people doing dumb things.' },
  { id: 'movies',   label: '🎬 Movies & TV',    desc: 'Trivia for people with no real hobbies.' },
  { id: 'sports',   label: '🏆 Sports',         desc: 'For people who live vicariously.' },
  { id: 'darkhumor',label: '😈 Dark Humor',     desc: 'Not for the emotionally fragile.' },
]

export const QUESTIONS = {
  general: [
    { q: "What's the capital of Australia? (No, it's not Sydney, genius.)", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], answer: 2 },
    { q: "How many sides does a triangle have? (Please get this right.)", options: ["2", "3", "4", "5"], answer: 1 },
    { q: "Water boils at what temperature? (At sea level, not on Mars.)", options: ["90°C", "95°C", "100°C", "110°C"], answer: 2 },
    { q: "What planet is closest to the Sun?", options: ["Venus", "Mercury", "Earth", "Mars"], answer: 1 },
    { q: "How many bones are in the adult human body?", options: ["196", "206", "216", "226"], answer: 1 },
    { q: "What's the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
    { q: "What year did World War II end?", options: ["1943", "1944", "1945", "1946"], answer: 2 },
    { q: "What's the square root of 144?", options: ["11", "12", "13", "14"], answer: 1 },
    { q: "Which country invented pizza? (Hint: not America.)", options: ["France", "Spain", "Italy", "Greece"], answer: 2 },
    { q: "How many days are in a leap year?", options: ["364", "365", "366", "367"], answer: 2 },
  ],
  science: [
    { q: "What's the chemical symbol for gold? (It's not G, smartass.)", options: ["Go", "Gd", "Au", "Ag"], answer: 2 },
    { q: "DNA stands for...?", options: ["Daily Nonsense Accumulation", "Deoxyribonucleic Acid", "Dynamic Neural Array", "Distributed Nucleic Algorithm"], answer: 1 },
    { q: "How many chromosomes do humans have?", options: ["44", "46", "48", "50"], answer: 1 },
    { q: "What's the speed of light (approx)?", options: ["200,000 km/s", "250,000 km/s", "300,000 km/s", "350,000 km/s"], answer: 2 },
    { q: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], answer: 1 },
    { q: "What organ produces insulin?", options: ["Liver", "Kidney", "Pancreas", "Spleen"], answer: 2 },
    { q: "What's the atomic number of carbon?", options: ["4", "6", "8", "12"], answer: 1 },
    { q: "Which gas makes up ~78% of Earth's atmosphere?", options: ["Oxygen", "CO2", "Nitrogen", "Argon"], answer: 2 },
    { q: "What's the powerhouse of the cell? (You better know this.)", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi Body"], answer: 2 },
    { q: "How old is the Earth (approx)?", options: ["2.5 billion years", "4.5 billion years", "6.5 billion years", "8.5 billion years"], answer: 1 },
  ],
  history: [
    { q: "Who was the first US President? (Please don't say Obama.)", options: ["John Adams", "Benjamin Franklin", "George Washington", "Thomas Jefferson"], answer: 2 },
    { q: "In what year did the Titanic sink?", options: ["1910", "1911", "1912", "1913"], answer: 2 },
    { q: "Which empire was ruled by Julius Caesar?", options: ["Greek", "Ottoman", "Roman", "Byzantine"], answer: 2 },
    { q: "The Berlin Wall fell in what year?", options: ["1987", "1988", "1989", "1990"], answer: 2 },
    { q: "Who painted the Mona Lisa?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Donatello"], answer: 2 },
    { q: "What ancient wonder was located in Alexandria?", options: ["The Colossus", "The Lighthouse", "The Hanging Gardens", "The Mausoleum"], answer: 1 },
    { q: "The French Revolution began in what year?", options: ["1776", "1783", "1789", "1799"], answer: 2 },
    { q: "Which country dropped the first atomic bomb?", options: ["USSR", "UK", "USA", "Germany"], answer: 2 },
    { q: "Who was the last pharaoh of ancient Egypt?", options: ["Nefertiti", "Cleopatra", "Hatshepsut", "Isis"], answer: 1 },
    { q: "The Great Wall of China was primarily built to keep out whom?", options: ["Japanese", "Koreans", "Mongols", "Russians"], answer: 2 },
  ],
  movies: [
    { q: "Who played Iron Man in the MCU? (If you don't know this, leave.)", options: ["Chris Evans", "Chris Hemsworth", "Robert Downey Jr.", "Mark Ruffalo"], answer: 2 },
    { q: "In The Matrix, which pill does Neo take?", options: ["Blue", "Red", "Green", "Purple"], answer: 1 },
    { q: "What's the highest-grossing film of all time?", options: ["Titanic", "Avengers: Endgame", "Avatar", "Star Wars"], answer: 2 },
    { q: "Who directed Pulp Fiction?", options: ["Martin Scorsese", "Quentin Tarantino", "Christopher Nolan", "David Fincher"], answer: 1 },
    { q: "What year was the first Star Wars film released?", options: ["1975", "1976", "1977", "1978"], answer: 2 },
    { q: "In Breaking Bad, what's Walter White's street name?", options: ["The Cook", "Heisenberg", "El Jefe", "Blue Sky"], answer: 1 },
    { q: "Which movie features the line 'I see dead people'?", options: ["The Shining", "Poltergeist", "The Sixth Sense", "Beetlejuice"], answer: 2 },
    { q: "What does 'E.T.' stand for in the Spielberg film?", options: ["Extra Terrestrial", "External Traveler", "Exotic Thing", "Eternal Time"], answer: 0 },
    { q: "Who voiced Simba in the original Lion King?", options: ["Will Smith", "Eddie Murphy", "Matthew Broderick", "James Earl Jones"], answer: 2 },
    { q: "What sport is featured in 'Whiplash'?", options: ["Piano", "Violin", "Drums", "Trumpet"], answer: 2 },
  ],
  sports: [
    { q: "How many players are on a soccer team? (On the field, genius.)", options: ["9", "10", "11", "12"], answer: 2 },
    { q: "Which country has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Italy", "Brazil"], answer: 3 },
    { q: "How long is a standard marathon?", options: ["40km", "42.195km", "44km", "45km"], answer: 1 },
    { q: "In tennis, what comes after deuce?", options: ["Game", "Set", "Advantage", "Match"], answer: 2 },
    { q: "How many rings are on the Olympic flag?", options: ["4", "5", "6", "7"], answer: 1 },
    { q: "Which sport uses a shuttlecock?", options: ["Squash", "Racquetball", "Badminton", "Pickleball"], answer: 2 },
    { q: "Michael Jordan played for which NBA team?", options: ["LA Lakers", "Boston Celtics", "Chicago Bulls", "Miami Heat"], answer: 2 },
    { q: "How many points is a touchdown worth in American football?", options: ["4", "5", "6", "7"], answer: 2 },
    { q: "What country invented basketball?", options: ["USA", "Canada", "UK", "Australia"], answer: 0 },
    { q: "A perfect score in bowling is called a...?", options: ["300", "Perfect game", "Turkey", "Strike out"], answer: 0 },
  ],
  darkhumor: [
    { q: "What do you call a fish without eyes?", options: ["Blind fish", "Fsh", "A dead fish", "An eel"], answer: 1 },
    { q: "What's the most dangerous part of a hospital?", options: ["The ICU", "The parking lot", "The gift shop prices", "The cafeteria food"], answer: 2 },
    { q: "Why can't you hear a pterodactyl go to the bathroom?", options: ["They're extinct", "The P is silent", "They use sign language", "They don't have bladders"], answer: 1 },
    { q: "What do you call someone who can't stop buying carpets?", options: ["Floored", "Rugged", "Hooked", "A hoarder"], answer: 0 },
    { q: "I told my doctor I broke my arm in two places. What did he say?", options: ["Go to the ER", "Stop going to those places", "File a lawsuit", "Take two aspirin"], answer: 1 },
    { q: "What's the difference between a good joke and a bad joke timing?", options: ["The punchline", "The audience", "Nothing — it's all timing", "The delivery"], answer: 2 },
    { q: "Why did the scarecrow win an award?", options: ["He was outstanding in his field", "He scared everyone into submission", "Nobody else applied", "He had a great agent"], answer: 0 },
    { q: "What do you call cheese that isn't yours?", options: ["Stolen property", "Nacho cheese", "Free cheese", "Borrowed dairy"], answer: 1 },
    { q: "My wife told me to stop acting like a flamingo. I had to put my foot down.", options: ["Classic", "Terrible", "Both", "She was right"], answer: 2 },
    { q: "Why don't scientists trust atoms?", options: ["They're too small", "They make up everything", "They have no morals", "They split when stressed"], answer: 1 },
  ],
}

export function getQuestions(categoryId, count = 8) {
  const qs = QUESTIONS[categoryId] || QUESTIONS.general
  return [...qs].sort(() => Math.random() - 0.5).slice(0, Math.min(count, qs.length))
}
